name: Deploy to GitHub Pages

on:
  push:
    branches:
      - master
  workflow_dispatch:
    inputs:
      update_message:
        description: '更新说明'
        required: false
        default: '手动更新数据'
  # 添加定时触发 - 每小时检查一次
  schedule:
    - cron: '0 * * * *'

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    env:
      NOTION_PAGE_ID: ${{ secrets.NOTION_PAGE_ID }}
      NOTION_TOKEN: ${{ secrets.NOTION_TOKEN }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Show current commit
        run: git log -1

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 10.4.1

      - name: Get pnpm store directory
        shell: bash
        run: |
          echo "STORE_PATH=$(pnpm store path --silent)" >> $GITHUB_ENV

      # - name: Setup pnpm cache
      #   uses: actions/cache@v3
      #   with:
      #     path: ${{ env.STORE_PATH }}
      #     key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
      #     restore-keys: |
      #       ${{ runner.os }}-pnpm-store-

      - name: Install dependencies
        run: rm -rf node_modules pnpm-lock.yaml && pnpm install

      - name: Check critters install
        run: pnpm ls critters

      - name: Clean all build cache
        run: |
          rm -rf apps/web/.next apps/web/out node_modules/.cache ~/.pnpm-store

      - name: Build
        run: pnpm run build

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./apps/web/out
          force_orphan: true